Add option to build without libertine
ubports/content-hub pull request #14
Opened 2020-09-10 22:44 UTC by mariogrip

2020-09-22 18:17 UTC, Flohack74 commented
Is this a preparation to fix content-hub for the Pinephone (and all other Non-Android devices) ?

2020-09-25 17:09 UTC, dobey commented
> Is this a preparation to fix content-hub for the Pinephone (and all other Non-Android devices) ?

No, this is only for non-ubuntu distros where Libertine doesn't make sense and doesn't work.

2020-10-05 13:15 UTC, Flohack74 approved these changes, later dismissed

2020-10-05 13:15 UTC, Flohack74 commented
LGTM @mariogrip

2020-10-05 13:40 UTC, dobey requested changes

2020-10-05 13:40 UTC, dobey commented on CMakeLists.txt
> +   message("Bulding with libertine support")
Typo. _Bulding_ instead of _Building_.

2020-10-07 20:42 UTC, dobey approved these changes

2020-10-07 20:42 UTC, dobey commented on CMakeLists.txt
> +   message("Bulding with libertine support")
Fixed this directly to move things along.

2020-10-07 20:58 UTC, merged